<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SWQA-NV-LEN" failures="1" tests="3" name="Pixel_9" time="46.371" errors="0" timestamp="2025-09-15T09:51:17 PDT">
  <testcase classname="com.qa.tests.LoginTests" name="invalidPassword" time="12.99"/>
  <testcase classname="com.qa.tests.LoginTests" name="invalidUserNameTest" time="3.081">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.DSDS]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.DSDS]
at com.qa.tests.LoginTests.invalidUserNameTest(LoginTests.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:132)
at java.base/java.util.concurrent.AbstractExecutorService.newTaskFor(AbstractExecutorService.java:113)
at java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:274)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- invalidUserNameTest -->
  <testcase classname="com.qa.tests.LoginTests" name="successfulLogin" time="3.763"/>
</testsuite> <!-- Pixel_9 -->
